#!/bin/bash 

#this script uses geocoder from https://github.com/DenisCarriere/geocoder

[ -n "$1" ] && input="$1" || input=StatCounter-Log.csv

cities=$(statcounter_report -p -t'"^"$8","$9","$10' \
            <(awk -f cities_spells_fix.awk $input) |
            awk -F\| '{print $2","$1}'
        )

echo "Country,Region,City,Count,Longitude,Lattitude"
IFS=$'\n'
for c in $cities
do
    c0=$(echo $c | sed 's/\(.*\), *\([0-9]\+\) *$/\1,\2/')
    c1=$(echo $c0 | sed 's/,[^,]\+$//')
    ll=$(geocode -o wkt \"$c1\" | sed 's/^"POINT(//; s/)"$//; s/ /,/')
    echo "$c0,$ll"
done

