#!/bin/bash 

#this script uses geocoder from https://github.com/DenisCarriere/geocoder

geocode=
provider="osm"
back="Count"
spell_fix_cmd="-e {print}"

while getopts 'gp:f:' opt ; do
    case $opt in
        g) geocode=1 back="Longitude;Lattitude" ;;
        p) #run geocode --help to see the list of all providers
           provider="$OPTARG" ;;
        f) spell_fix_cmd="-f $OPTARG" ;;
       \?) echo "Invalid option: -$OPTARG" >&2
           exit 1 ;;
        :) echo "Option -$OPTARG requires an argument" >&2
           exit 1 ;;
    esac
done

shift $((OPTIND-1))
[ -n "$1" ] && input="$1" || input=-

cities=$(awk $spell_fix_cmd "$input" |
            statcounter_report -p -t'"^"$8";"$9";"$10' |
            awk -F\| '{gsub(/^[ \t]+|[ \t]+$/, "", $1); print $2";"$1}'
        )

echo "Country;Region;City;$back"
IFS=$'\n'
for c in $cities
do
    if [ -n "$geocode" ]
    then
        c0="${c%;*}"
        ll=$(geocode -p "$provider" -o wkt \""$c0"\" |
                sed 's/^"POINT(//; s/)"$//; s/ /;/'
            )
        echo "$c0;$ll"
    else
        echo "$c"
    fi
done

